// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { defineConfig } from "prisma/config";
import path from "node:path";

const defaultDatabaseUrl = `file:${path.join(process.cwd(), "backend/prisma/dev.db")}`;

function databaseUrl(): string {
  const url = process.env.DATABASE_URL || defaultDatabaseUrl;
  if (
    url === "file:./dev.db" ||
    url === "file:./prisma/dev.db" ||
    url === "file:./backend/prisma/dev.db"
  ) {
    return defaultDatabaseUrl;
  }
  return url;
}

export default defineConfig({
  schema: "backend/prisma/schema.prisma",
  datasource: {
    url: databaseUrl(),
  },
  migrations: {
    path: "backend/prisma/migrations",
  }
});
